### ISSUE TITLE
NoneType' object has no attribute 'publish

### ISSUE THREAD

**Issue by simskimz** [fmartinou/hassio-addons#14]
Hello, 
i'm facing this issue :

```
1668785762, "error": 0, "data": [{"name": "thermicLevel", "validity": "upToDate", "value": "ECO"}]}]}])
2023-10-25 13:15:31,355 - tydom.MessageHandler - ERROR   - 'NoneType' object has no attribute 'publish'
Traceback (most recent call last):
  File "/app/tydom/MessageHandler.py", line 360, in parse_response
    await self.parse_devices_data(parsed=parsed)
  File "/app/tydom/MessageHandler.py", line 470, in parse_devices_data
    await self.parse_endpoint_data(endpoint, i["id"])
  File "/app/tydom/MessageHandler.py", line 707, in parse_endpoint_data
    await new_sh_hvac.update()
  File "/app/sensors/Boiler.py", line 114, in update
    await self.setup()
  File "/app/sensors/Boiler.py", line 109, in setup
    self.mqtt.mqtt_client.publish(
```
Could you help me ?

**Comment by kassisto** [comment]
It's a mqtt connection configuration problem. 

Found the answer to your problem here :
https://github.com/tydom2mqtt/tydom2mqtt/issues/138

> So I solved it, by checking my configuration.
> 
> self.mqtt.mqtt_client.publish crashes if mqtt_client is null, which means that the mqtt connection was not done.
> 
> I changed and checked that my HA mosquitto was with the right username and password (it wasn't) and now I don't have the issue anymore displaying this publish error.
> 
> (However, I still have no devices created in MQTT, but that's another story/bug, unrelated to this one.)
